<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <title>Minuta de Constitución E.I.R.L. con </title>
</head>
<body>
  foreach ($data as $item)
    <h2>MINUTA DE CONSTITUCION E.I.R.L CON APORTES EN BIENES NO DINERARIOS</h2>
    <h2>SEÑOR  NOTARIO</h2>

    <p>SÍRVASE USTED EXTENDER EN SU REGISTRO DE ESCRITURAS PÚBLICAS UNA DE CONSTITUCIÓN DE EMPRESA INDIVIDUAL DE RESPONSABILIDAD LIMITADA,  QUE OTORGA: {{nombre}}, DE NACIONALIDAD {{nacionalidad}}, CON DOCUMENTO DE IDENTIDAD NUMERO {{dni}}, OCUPACION: {{profesion}}, ESTADO CIVIL: {{estado_civil}} 
    if ($estado_civil == 'casado')
      <p>CASADO(A) CON [NOMBRE DEL CÓNYUGE (DE SER CASADO)],  CON {{dni_conyuge}}, SEÑALANDO DOMICILIO PARA EFECTOS DE LA PRESENTE ESCRITURA EN {{direccion}}.</p>
    else
      <p>SEÑALANDO DOMICILIO PARA EFECTOS DE LA PRESENTE ESCRITURA EN {{direccion}}.</p>
    endif

    <p>PRIMERA.- POR EL PRESENTE, {{nombre}}: CONSTITUYE UNA EMPRESA INDIVIDUAL DE RESPONSABILIDAD LIMITADA BAJO LA DENOMINACIÓN DE: “{{nombre_empresa}} E.I.R.L.”, CON DOMICILIO EN {{direccion_empresa}}, PROVINCIA DE {{provincia_empresa}}, DEPARTAMENTO DE  {{departamento_empresa}}, QUE INICIA SUS OPERACIONES A PARTIR DE SU INSCRIPCIÓN EN EL REGISTRO MERCANTIL CON UNA DURACIÓN INDETERMINADA, PUDIENDO ESTABLECER SUCURSALES EN TODO EL TERRITORIO NACIONAL.</p>

    <p>SEGUNDA.- EL OBJETO DE LA EMPRESA ES: {{objetivo}}, SE ENTIENDEN INCLUIDOS EN EL OBJETO, LOS ACTOS RELACIONADOS CON EL MISMO, QUE COADYUVEN A LA REALIZACIÓN DE SUS FINES EMPRESARIALES. PARA CUMPLIR DICHO OBJETO, PODRÁ REALIZAR TODOS AQUELLOS ACTOS Y CONTRATOS QUE SEAN LÍCITOS, SIN RESTRICCIÓN ALGUNA.</p>

    <p>TERCERA.- EL CAPITAL DE LA EMPRESA ES DE S/. {{monto_capital}}. CONSTITUIDO POR APORTES DEL TITULAR EN BIENES; EFECTUADOS DEL SIGUIENTE MODO:
      foreach ($aportes as $aporte)
        <ul>
          <p>- {{aporte.descripcion}}: S/. {{aporte.monto}}</p>
          <p><b>otal Aportado</b> <b>{{total_aportado}}</b></p>
        </ul>
      endforeach
      ESTOS BIENES SE DETALLAN EN LA DECLARACIÓN JURADA QUE SE ANEXA A LA PRESENTE Y FORMA PARTE INTEGRANTE DE LA ESCRITURA PUBLICA QUE ESTE DOCUMENTO ORIGINE
    </p>

    <p>CUARTA.- SON ÓRGANOS DE LA EMPRESA: EL TITULAR Y LA GERENCIA. EL RÉGIMEN QUE LE CORRESPONDA ESTÁ SEÑALADO EN EL DECRETO LEY Nº 21621, ARTÍCULOS 39 Y 50 RESPECTIVAMENTE Y DEMÁS NORMAS MODIFICATORIAS Y COMPLEMENTARIAS.</p>
    
    <p>QUINTA.- LA GERENCIA ES EL ÓRGANO QUE TIENE A SU CARGO LA ADMINISTRACIÓN Y REPRESENTACIÓN DE LA EMPRESA. SERÁ DESEMPEÑADA POR UNA O MÁS PERSONAS NATURALES. EL CARGO DE GERENTE ES INDELEGABLE. EN CASO DE QUE EL CARGO DE GERENTE RECAIGA EN EL TITULAR, ÉSTE SE DENOMINARÁ TITULAR GERENTE.</p>

    <p>SEXTA.- LA DESIGNACIÓN DEL GERENTE SERÁ EFECTUADA POR EL TITULAR, LA DURACIÓN DEL CARGO ES INDEFINIDA, AUNQUE PUEDE SER REVOCADO EN CUALQUIER MOMENTO.</p>

    <p>SEPTIMA.- CORRESPONDE AL GERENTE</p>
    <p>1. ORGANIZAR EL RÉGIMEN INTERNO DE LA EMPRESA.
      2. CELEBRAR CONTRATOS INHERENTES AL OBJETO DE LA EMPRESA, FIJANDO SUS CONDICIONES; SUPERVISAR Y FISCALIZAR EL DESARROLLO DE LAS ACTIVIDADES DE LA EMPRESA.
      3. REPRESENTAR A LA EMPRESA ANTE TODA CLASE DE AUTORIDADES. EN LO JUDICIAL GOZARA DE LAS FACULTADES GENERALES Y ESPECIALES, SEÑALADAS EN LOS ARTÍCULOS 74º, 75º, 77º Y 436º DEL CÓDIGO PROCESAL CIVIL. EN LO ADMINISTRATIVO GOZARÁ DE LA FACULTAD DE REPRESENTACIÓN PREVISTA EN EL ARTICULO 115º DE LA LEY Nº 27444 Y DEMÁS NORMAS CONEXAS Y COMPLEMENTARIAS. TENIENDO EN TODOS LOS CASOS FACULTAD DE DELEGACIÓN O SUSTITUCIÓN. ADEMÁS PODRÁ CONSTITUIR PERSONAS JURÍDICAS EN NOMBRE DE LA EMPRESA Y REPRESENTAR A LA EMPRESA ANTE LAS PERSONAS JURÍDICAS QUE CREA CONVENIENTE Y DEMÁS NORMAS COMPLEMENTARIAS. ADEMÁS PODRÁ SOMETER LAS CONTROVERSIAS A ARBITRAJE, CONCILIACIONES EXTRAJUDICIALES Y DEMÁS MEDIOS ADECUADOS DE SOLUCIÓN DE CONFLICTO, PUDIENDO SUSCRIBIR LOS DOCUMENTOS QUE SEAN PERTINENTES.
      4. CUIDAR LOS ACTIVOS DE LA EMPRESA.
      5. ABRIR Y CERRAR CUENTAS CORRIENTES, BANCARIAS, MERCANTILES Y
      GIRAR CONTRA LAS MISMAS, COBRAR Y ENDOSAR CHEQUES DE LA EMPRESA, ASÍ COMO ENDOSAR Y DESCONTAR DOCUMENTOS DE CRÉDITO. SOLICITAR SOBREGIROS, PRÉSTAMOS, CRÉDITOS O FINANCIACIONES PARA DESARROLLAR EL OBJETO CELEBRANDO LOS CONTRATOS RESPECTIVOS.
      6. SOLICITAR TODA CLASE DE PRÉSTAMOS CON GARANTÍAS HIPOTECARIA, PRENDARIA Y DE CUALQUIER FORMA, ADEMÁS CONOCIMIENTO DE EMBARQUE, CARTA DE PODER, CARTA FIANZA, PÓLIZA, LETRAS DE CAMBIO, PAGARES, FACTURAS CONFORMADAS Y CUALQUIER OTRO TÍTULO VALOR.
      7. SUSCRIBIR CONTRATOS DE ARRENDAMIENTO Y SUBARRENDAMIENTO. 8. COMPRAR Y VENDER LOS BIENES SEAN MUEBLES O INMUEBLES DE LA EMPRESA, SUSCRIBIENDO LOS RESPECTIVOS CONTRATOS.
      9. CELEBRAR, SUSCRIBIR CONTRATOS DE LEASING O ARRENDAMIENTO FINANCIERO, CONSORCIO, ASOCIACIÓN EN PARTICIPACIÓN Y CUALQUIER OTRO CONTRATO DE COLABORACIÓN EMPRESARIAL, VINCULADOS AL OBJETO DE LA EMPRESA.
      10. AUTORIZAR A SOLA FIRMA, LA ADQUISICIÓN DE BIENES, CONTRATACIÓN DE OBRAS Y PRESTACIÓN DE SERVICIOS PERSONALES.
      11. NOMBRAR, PROMOVER, SUSPENDER Y DESPEDIR A LOS EMPLEADOS Y SERVIDORES DE LA EMPRESA.
      12. CONCEDER LICENCIA AL PERSONAL DE LA EMPRESA.
      13. CUIDAR DE LA CONTABILIDAD Y FORMULAR EL ESTADO DE PÉRDIDAS Y GANANCIAS, EL BALANCE GENERAL DE LA EMPRESA Y LOS DEMÁS ESTADOS Y ANÁLISIS CONTABLES QUE SOLICITE EL TITULAR.
      14. SOLICITAR, ADQUIRIR, TRANSFERIR REGISTROS DE PATENTES, MARCAS, NOMBRES COMERCIALES CONFORME A LEY, SUSCRIBIENDO CUALQUIER CLASE DE DOCUMENTOS VINCULADOS, QUE CONLLEVE A LA REALIZACIÓN DEL OBJETO.
      15. PARTICIPAR EN LICITACIONES, CONCURSOS PÚBLICOS Y/O ADJUDICACIONES, SUSCRIBIENDO LOS RESPECTIVOS DOCUMENTOS, QUE CONLLEVE A LA REALIZACIÓN DEL OBJETO DE LA EMPRESA.
    </p>

    <p>OCTAVA.- PARA TODO LO NO PREVISTO RIGEN LAS DISPOSICIONES CONTENIDAS EN EL D.L. Nº 21621 Y AQUELLAS QUE LAS MODIFIQUEN O COMPLEMENTEN.</p>

    <p>DISPOSICION TRANSITORIA.- {{nombre}}, IDENTIFICADO CON DNI Nº {{dni}},  EJERCERÁ EL CARGO DE TITULAR GERENTE DE LA EMPRESA, PERUANO, CON DOMICILIO SEÑALADO EN LA INTRODUCCION DE LA PRESENTE.
    ASI MISMO, SE NOMBRA COMO APODERADO A {{apoderado}}, IDENTIFICADO CON DOCUMENTO DE IDENTIDAD DNI , CON NUMERO : {{dni_apoderado}} QUIEN TENDRÁ LAS MISMAS FACULTADES QUE EL GERENTE</p>

    <p>CLAUSULA ADICIONAL I.- DE CONFORMIDAD AL ARTICULO 315 DEL CÓDIGO CIVIL, INTERVIENE 
      if(estado_civil == 'casado')
      {{nombre_conyuge}} , CÓNYUGE DE {{nombre}}, AUTORIZANDO EXPRESAMENTE EL APORTE EN BIENES NO DINERARIOS.
      else
      {{nombre}}, EN SU CALIDAD DE TITULAR DE LA EMPRESA, AUTORIZANDO EXPRESAMENTE EL APORTE EN BIENES NO DINERARIOS.
    </p>

    <p>{{ciudad}},{{fecha_registro}}.</p>

    <h2><b>DECLARACIÓN JURADA DE APORTE DE BIENES</b></h2>

    <p>POR EL PRESENTE DOCUMENTO: YO,{{nombre}}  IDENTIFICADO CON D.N.I. Nº  {{dni}}, CON DOMICILIO EN {{direccion}} PROVINCIA DE {{provincia}} Y DEPARTAMENTO DE {{departamento}}, EN MI CALIDAD DE TITULAR GERENTE DESIGNADO DE LA EMPRESA DENOMINADA:“{{nombre_empresa}} E.I.R.L. QUE SE CONSTITUYE, DECLARO BAJO JURAMENTO HABER RECIBIDO LOS BIENES MUEBLES QUE A CONTINUACIÓN SE PRECISA, COMO APORTE AL CAPITAL DE LA PRECITADA EMPRESA:</p>
    <p>DETALLE DE LOS BIENES VALOR ASIGNADO S/.</p>
    foreach ($aportes as $aporte)
      <ul>
        <p>- {{aporte.descripcion}}: S/. {{aporte.monto}}</p>
      </ul>
    endforeach

    <p>LO QUE HACE UN TOTAL GENERAL DE S/ {{monto_total}}.{{total_letras}}, COMO APORTE EN BIENES MUEBLES AL CAPITAL DE LA EMPRESA.</p>

    <p>{{ciudad}},{{fecha_registro_letras}}.</p>

    <p>FIRMA DEL TITULAR GERENTE</p>

  endforeach
</body>
</html>
